### ISSUE TITLE
compilation issue on aarch64 ubuntu

### ISSUE THREAD

**Issue by fwflunky** [Deniskore/llvm#1]
hi, clang 14 unable to compile llvm/Transforms/Obfuscate/XorShift.h because __rdtsc ((x)intrin.h) doesn't exist on arm. I think fix is replacing __rdtsc() with __builtin_readcyclecounter()

**Comment by Deniskore** [comment]
Hi @fwflunky, If I make the changes, can you test it?

**Comment by fwflunky** [comment]
> Hi @fwflunky, If I make the changes, can you test it?

yes

**Comment by fwflunky** [comment]
Hi, im too late (XD), but now i successfully builded this obfuscator with clang
